# ============================================================================
# Google Cloud Functions Configuration
# ============================================================================
# 
# Upload Asset Function - Uploads files to GCS bucket with hierarchical paths
#

name: uploadAsset
entry_point: uploadAsset
runtime: nodejs20
trigger: http
region: us-central1
memory: 512MB
timeout: 300s
max_instances: 10
env_vars: UPLOAD_API_KEY=espaze_secure_key_2025_prod_v1
---
# Trigger deployment





